//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAndes.ICC5103._202301.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Historial
    {
        public int Id { get; set; }
        public int IdEnajenacion { get; set; }
        public int Comuna { get; set; }
        public int Manzana { get; set; }
        public int Predio { get; set; }
        public int Fojas { get; set; }
        public System.DateTime FechaInscripcion { get; set; }
        public int IdInscripcion { get; set; }
        public string Rut { get; set; }
        public double Porcentaje { get; set; }
        public int CNE { get; set; }
        public bool Check { get; set; }
        public string Participante { get; set; }
    
        public virtual Enajenacion Enajenacion { get; set; }
    }
}
