
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace UAndes.ICC5103._202301.Models
{

using System;
    using System.Collections.Generic;
    
public partial class VistaEnajenacion
{

    public int Id { get; set; }

    public string CNE { get; set; }

    public string Comuna { get; set; }

    public int Manzana { get; set; }

    public int Predio { get; set; }

    public string RutEnajenante { get; set; }

    public int PorcentajeEnajenante { get; set; }

    public int CheckEnajenante { get; set; }

    public string RutAdquiriente { get; set; }

    public int PorcentajeAdquiriente { get; set; }

    public int CheckAdquiriente { get; set; }

    public int Fojas { get; set; }

    public System.DateTime FechaInscripcion { get; set; }

    public Nullable<int> IdInscripcion { get; set; }

}

}
